### ISSUE TITLE
Typo in home page

### ISSUE THREAD

**Issue by ronitrajfr** [8rxn/portfolio#3]
So I was going through your portfolio and there was a typo
![image](https://github.com/8rxn/portfolio/assets/157343700/a2d73bf2-2202-4857-9d26-8844abd33c12)
Look at the spelling of `build`. It is in `Hero.jsx`.

But overall your portfolio looks awesome. Wishing You luck ahead!

**Comment by 8rxn** [comment]
Hey @rrajofficial7 
Thanks for pointing it out.

I'd like to mention that it's an intentional spelling, common in the web3 space

Still great catch 👁
